version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo_ecommerce
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: backend
    restart: always
    depends_on:
      - mongo
    ports:
      - "5001:5000"
    environment:
      MONGO_URI: "mongodb://mongo:27017/ecommerce"

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3001:80"

volumes:
  mongo_data:


